"""baseline schema

Revision ID: d191ecad2a39
Revises: 
Create Date: 2026-08-24 06:39:32.452018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd191ecad2a39'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('epics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('raw_user_prompt', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graph_edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_fqn', sa.String(length=512), nullable=False),
    sa.Column('target_fqn', sa.String(length=512), nullable=False),
    sa.Column('relation_type', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_edges_source_fqn'), 'graph_edges', ['source_fqn'], unique=False)
    op.create_index(op.f('ix_graph_edges_target_fqn'), 'graph_edges', ['target_fqn'], unique=False)
    op.create_table('graph_nodes',
    sa.Column('fqn', sa.String(length=512), nullable=False),
    sa.Column('node_type', sa.String(length=32), nullable=False),
    sa.Column('filepath', sa.String(length=512), nullable=False),
    sa.Column('stub_code', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('fqn')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('epic_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('assigned_model', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('target_files', sa.JSON(), nullable=False),
    sa.Column('read_set', sa.JSON(), nullable=False),
    sa.Column('write_set', sa.JSON(), nullable=False),
    sa.Column('dependencies', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['epic_id'], ['epics.id'], ),
    sa.PrimaryKeyConstraint('id', 'epic_id')
    )
    op.create_table('lock_audits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('epic_id', sa.String(length=36), nullable=False),
    sa.Column('filepath', sa.String(length=512), nullable=False),
    sa.Column('lock_type', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id', 'epic_id'], ['tasks.id', 'tasks.epic_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_costs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('epic_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('usd_cost', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id', 'epic_id'], ['tasks.id', 'tasks.epic_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_costs')
    op.drop_table('lock_audits')
    op.drop_table('tasks')
    op.drop_table('graph_nodes')
    op.drop_index(op.f('ix_graph_edges_target_fqn'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_source_fqn'), table_name='graph_edges')
    op.drop_table('graph_edges')
    op.drop_table('epics')
    # ### end Alembic commands ###
